basePath: /api/v1
definitions:
  response.PaginatedResponse:
    properties:
      data: {}
      message:
        type: string
      pagination:
        $ref: '#/definitions/response.Pagination'
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
  response.Pagination:
    properties:
      hasNext:
        type: boolean
      hasPrev:
        type: boolean
      limit:
        type: integer
      page:
        type: integer
      totalItems:
        type: integer
      totalPages:
        type: integer
    type: object
  response.Response:
    properties:
      data: {}
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@apihub.com
    name: API Support
    url: https://github.com/ultimatum/apihub_go
  description: A comprehensive API hub with multiple API categories for learning and
    development
  license:
    name: ISC
    url: https://opensource.org/licenses/ISC
  termsOfService: http://swagger.io/terms/
  title: FreeAPI - API Hub
  version: "1.0"
paths:
  /public/dogs:
    get:
      consumes:
      - application/json
      description: Get a paginated list of dog breeds
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedResponse'
      summary: Get all dog breeds
      tags:
      - Public APIs
  /public/dogs/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific dog breed by its ID
      parameters:
      - description: Dog ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get dog breed by ID
      tags:
      - Public APIs
  /public/dogs/random:
    get:
      consumes:
      - application/json
      description: Get a randomly selected dog breed
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a random dog breed
      tags:
      - Public APIs
  /public/meals:
    get:
      consumes:
      - application/json
      description: Get a paginated list of meals
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedResponse'
      summary: Get all meals
      tags:
      - Public APIs
  /public/meals/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific meal by its ID
      parameters:
      - description: Meal ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get meal by ID
      tags:
      - Public APIs
  /public/meals/random:
    get:
      consumes:
      - application/json
      description: Get a randomly selected meal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a random meal
      tags:
      - Public APIs
  /public/quotes:
    get:
      consumes:
      - application/json
      description: Get a paginated list of quotes
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedResponse'
      summary: Get all quotes
      tags:
      - Public APIs
  /public/quotes/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific quote by its ID
      parameters:
      - description: Quote ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get quote by ID
      tags:
      - Public APIs
  /public/quotes/random:
    get:
      consumes:
      - application/json
      description: Get a randomly selected quote
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a random quote
      tags:
      - Public APIs
  /public/randomjokes:
    get:
      consumes:
      - application/json
      description: Get a paginated list of random jokes
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedResponse'
      summary: Get all random jokes
      tags:
      - Public APIs
  /public/randomjokes/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific random joke by its ID
      parameters:
      - description: Joke ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get random joke by ID
      tags:
      - Public APIs
  /public/randomjokes/random:
    get:
      consumes:
      - application/json
      description: Get a randomly selected joke
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a random joke
      tags:
      - Public APIs
  /public/randomusers:
    get:
      consumes:
      - application/json
      description: Get a paginated list of random users
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedResponse'
      summary: Get all random users
      tags:
      - Public APIs
  /public/randomusers/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific random user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get random user by ID
      tags:
      - Public APIs
  /public/randomusers/random:
    get:
      consumes:
      - application/json
      description: Get a randomly selected user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a random user
      tags:
      - Public APIs
  /public/stocks:
    get:
      consumes:
      - application/json
      description: Get a paginated list of NSE stocks
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedResponse'
      summary: Get all stocks
      tags:
      - Public APIs
  /public/stocks/{symbol}:
    get:
      consumes:
      - application/json
      description: Get a specific stock by its symbol (e.g., TCS, RELIANCE)
      parameters:
      - description: Stock Symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get stock by symbol
      tags:
      - Public APIs
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
